services:
  frontend:
    build: ./frontend
    image: src/frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_BACKEND_URL: "http://backend:8000"
    ports:
      - "5173:4173"
    depends_on:
      - backend
    container_name: frontend
    command: npm run preview -- --host 0.0.0.0
    networks:
      - app-tier
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "frontend-log"
    # Save logs to a file on the host machine
    volumes:
      - ./logs:/var/lib/docker/containers


  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KXQDTu5XrbsVDhe
      POSTGRES_DB: ponerada
    ports:
      - "5433:5432"
    networks:
      - app-tier
    volumes:
      - ./postgres:/var/lib/postgresql/data
    container_name: postgres
    restart: unless-stopped


  backend:
    build: ./backend
    image: src/backend
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://postgres:KXQDTu5XrbsVDhe@postgres:5432/fillmore"
      TF_ENABLE_ONEDNN_OPTS: 0
      POCKETBASE_URL: "http://pocketbase:8090"
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    container_name: backend
    networks:
      - app-tier
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "backend-log"
    volumes:
      - ./logs:/var/lib/docker/containers

networks:
  app-tier:
    driver: bridge